import sqlite3, os

databaseFile = "Database.db"

if(os.path.exists(databaseFile)):
    os.remove(databaseFile)

DB = sqlite3.connect(databaseFile)
c = DB.cursor()

c.execute("CREATE TABLE 'ADMIN' ('USERNAME' TEXT NOT NULL UNIQUE, 'PASSWORD' TEXT NOT NULL, 'EMAIL' TEXT NOT NULL, 'TOKEN' TEXT DEFAULT NULL, PRIMARY KEY('USERNAME'))")
c.execute("CREATE TABLE 'CLIENTS' ('ID' TEXT NOT NULL, 'ONLINE' INTEGER DEFAULT 0, 'IP' TEXT DEFAULT NULL, 'LASTSEEN' TEXT DEFAULT CURRENT_TIMESTAMP, 'PERSISTANCE' INTEGER DEFAULT 0, PRIMARY KEY('ID'))")
c.execute("CREATE TABLE 'INFORMATION' ('ID' TEXT NOT NULL, 'NAME' TEXT DEFAULT NULL, 'USER' TEXT DEFAULT NULL, 'OS' TEXT DEFAULT NULL, 'LANG' TEXT DEFAULT NULL, 'CPU' TEXT DEFAULT NULL, 'GPU' TEXT DEFAULT NULL, 'RAM' TEXT DEFAULT NULL, 'DISK' TEXT DEFAULT NULL, 'JSON' TEXT DEFAULT NULL)")
c.execute("CREATE TABLE 'QUEUE' ('COMMAND_ID' TEXT NOT NULL UNIQUE, 'CLIENT_ID' TEXT NOT NULL, 'COMMAND' TEXT NOT NULL, 'RESPONSE' BLOB DEFAULT NULL, 'FILEPATH' TEXT DEFAULT NULL, 'STATUS' INTEGER NOT NULL DEFAULT 0, PRIMARY KEY('COMMAND_ID','CLIENT_ID'))")
#c.execute("CREATE TABLE 'HISTORY' ('CLIENT_ID' TEXT NOT NULL, 'TEXT' TEXT, SENT INT DEFAULT 0)")

DB.commit()
DB.close()
print("Database successfully created!")